export type VolunteerEvent = {
    slug: string;
    title: string;
    date: Date;
    location: string;
    about: string;
    isFinished: boolean;
}

export const eventList:VolunteerEvent[] = [
    {slug: "filler10", title:"Past Event", date: new Date("2023-03-12"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "filler11", title:"Past Event", date: new Date("2023-04-11"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "filler12", title:"Past Event", date: new Date('2023-01-18'), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "filler13", title:"Past Event", date: new Date("2023-10-28"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "filler14", title:"Past Event", date: new Date("2023-08-11"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "test", title:"Test", date: new Date("2024-04-10"), location: "behind you", about: "this is an example event c", isFinished: true},
    {slug: "filler1", title:"Event Name", date: new Date("2024-10-21"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: false},
    {slug: "filler2", title:"Event Name Nov-11", date: new Date("2024-11-11"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: false},
    {slug: "filler3", title:"Event Name", date: new Date('2024-04-18'), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "filler4", title:"Event Name", date: new Date("2024-05-28"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "filler5", title:"Event Name", date: new Date("2024-06-11"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "planting-trees", title:"Planting Trees", date: new Date("2024-01-01"), location: "Joao's House", about: "this is an example event a this is an example event a this is an example event a this is an example event a this is an example event a this is an example event a this is an example event a this is an example event a ", isFinished: true},
    {slug: "having-fun", title:"Having Fun", date: new Date("2024-02-03"), location: "my house", about: "Lorem ipsum dolor sit amet, veniam diceret eripuit qui an. Nostro nonumes recteque no has, soleat signiferumque vix ex. Minim accusam sed id, eros malis invidunt ius et. Per in errem ignota. Fugit habemus mediocrem vix ut, consul consetetur an cum", isFinished: true},
    {slug: "filler6", title:"Event Name", date: new Date("2024-06-01"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "filler7", title:"Event Name", date: new Date("2024-07-31"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "filler8", title:"Event Name", date: new Date("2024-11-11"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: false},
    {slug: "filler9", title:"Event Name", date: new Date("2024-08-05"), location: "Some Place", about: "this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event this is an example event.", isFinished: true},
    {slug: "last event", title:"Last Event", date: new Date("2025-01-04"), location: "The Last Place", about: "this is the last event in the list", isFinished: false}
]