name: Weekly PR from dev to prod

on:
  schedule:
    # Runs at 00:00 every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: prod
          base: dev
          title: 'Weekly merge from dev to prod'
          body: |
            This is an automated pull request to merge changes from the dev branch into the prod branch.
            Please review the changes and merge if everything looks good.
          labels: automated-pr
