name: Weekly Prod Sync

on:
  schedule:
    # Runs at 00:00 every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Sync prod with dev
        run: |
          git checkout prod
          git pull origin dev
          git commit -m "Weekly Sync"
          git push origin prod
